package io.github.chyuan_cuihongyuan.buzhou.guard.audit;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

/**
 * 审计记录 JDBC append-only 存储（impl-39 / spec 13 §T64）：与 buzhou-store-jdbc
 * 同一 {@link JdbcTemplate} 风格（SQL 常量 + {@code ?} 参数绑定），表结构自举
 * （CREATE TABLE IF NOT EXISTS，H2/MySQL/PostgreSQL 通用方言子集）。
 *
 * <p><b>append-only 纪律</b>：本类只发 INSERT/SELECT；没有 UPDATE/DELETE 路径——
 * 篡改防护的第一道墙是「写路径物理上不存在改删」。清理须由 DBA 经独立审批执行。
 */
public final class JdbcAuditRecordStore implements AuditRecordStore {

    private static final Logger LOG = LoggerFactory.getLogger(JdbcAuditRecordStore.class);

    /** 表结构自举 DDL（常量；identity 主键保证跨 H2/MySQL/PG 可用）。 */
    private static final String CREATE_TABLE_SQL = """
            CREATE TABLE IF NOT EXISTS buzhou_audit_record (
                seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                record_id VARCHAR(64) NOT NULL,
                ts BIGINT NOT NULL,
                agent_id VARCHAR(255) NOT NULL,
                agent_version VARCHAR(64) NOT NULL,
                session_id VARCHAR(255) NOT NULL,
                action_type VARCHAR(128) NOT NULL,
                action_detail CLOB,
                outcome VARCHAR(32) NOT NULL,
                trust_level VARCHAR(64),
                parent_record_id VARCHAR(64),
                prev_hash CHAR(64) NOT NULL,
                signature VARCHAR(128),
                key_version INT NOT NULL DEFAULT 0
            )""";

    private static final String INSERT_SQL = """
            INSERT INTO buzhou_audit_record
            (record_id, ts, agent_id, agent_version, session_id, action_type, action_detail,
             outcome, trust_level, parent_record_id, prev_hash, signature, key_version)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""";

    private static final String SELECT_ALL_SQL = """
            SELECT record_id, ts, agent_id, agent_version, session_id, action_type,
                   action_detail, outcome, trust_level, parent_record_id, prev_hash,
                   signature, key_version
            FROM buzhou_audit_record ORDER BY seq""";

    private static final String COUNT_SQL = "SELECT COUNT(*) FROM buzhou_audit_record";

    private static final RowMapper<AgentAuditRecord> MAPPER = (rs, rowNum) -> new AgentAuditRecord(
            rs.getString("record_id"), rs.getLong("ts"), rs.getString("agent_id"),
            rs.getString("agent_version"), rs.getString("session_id"),
            rs.getString("action_type"), rs.getString("action_detail"),
            rs.getString("outcome"), rs.getString("trust_level"),
            rs.getString("parent_record_id"), rs.getString("prev_hash"),
            rs.getString("signature"), rs.getInt("key_version"));

    private final JdbcTemplate jdbc;

    public JdbcAuditRecordStore(JdbcTemplate jdbcTemplate) {
        this.jdbc = jdbcTemplate;
        jdbc.execute(CREATE_TABLE_SQL);
        LOG.info("buzhou-guard 审计持久化就绪（table=buzhou_audit_record）");
    }

    @Override
    public void append(AgentAuditRecord record) {
        jdbc.update(INSERT_SQL,
                record.recordId(), record.timestamp(), record.agentId(),
                record.agentVersion(), record.sessionId(), record.actionType(),
                record.actionDetail(), record.outcome(), record.trustLevel(),
                record.parentRecordId(), record.prevHash(), record.signature(),
                record.keyVersion());
    }

    @Override
    public List<AgentAuditRecord> loadAll() {
        return jdbc.query(SELECT_ALL_SQL, MAPPER);
    }

    @Override
    public long count() {
        Long count = jdbc.queryForObject(COUNT_SQL, Long.class);
        return count == null ? 0L : count;
    }
}
